### PR TITLE
Update users.nix

### PR DESCRIPTION
**Pull request by rcturchetti**

### CODE REVIEW

**Comment by domenkozar** [comment]
Deployed, thanks!

**Comment by rcturchetti** [comment]
Thanks, more one question, now I am able to access this server:

ssh -p 2020 root@lab1.snabb.co  # Login to chur

I think it is down.


Prof. Rogério Turchetti
UFSM (Universidade Federal de Santa Maria)
Av. Roraima, 1000 - Bairro Camobi
Santa Maria - RS - CEP 97105-900
Tel. (+55) 55-3220-6102, Sala 301.
Fax: (+55) 55-3220-8006

**Comment by domenkozar** [comment]
@rcturchetti `chur` is currently separately updated. You should be able to use `lugano-1.snabb.co`, etc up to `lugano-4.snabb.co`

**Comment by rcturchetti** [comment]
Ok! Now it's working.
Thank for your help!
Turchetti

Prof. Rogério Turchetti
UFSM (Universidade Federal de Santa Maria)
Av. Roraima, 1000 - Bairro Camobi
Santa Maria - RS - CEP 97105-900
Tel. (+55) 55-3220-6102, Sala 301.
Fax: (+55) 55-3220-8006

**Pull request merged**
