### PR TITLE
Set indentation to two spaces everywhere

### PR DESCRIPTION
**Pull request by teknico**
Only change is indentation. Is there any linter that could enforce/mangle for us?

### CODE REVIEW

**Comment by domenkozar** [comment]
In general I'm very +1 for having readable, clean code.

But I'm skeptical merging this, as we have many branches that diverge from master and it's going to be major pain merging them back.

I'd say we give https://github.com/Gabriel439/nixfmt a go and format the code automatically as soon as `igalia` and `customchannel` branches are merged.

**Comment by teknico** [comment]
Yeah, conflicts are going to be a pain. Very glad that there's a tool for this! Hopefully it's good enough already, we could even call it from a pre-merge hook.

However I still need this change, so I'll put it in the `igalia` branch. Closing this PR.

**Comment by lukego** [comment]
JFYI: Git has [special support for merging whitespace conflicts](http://stackoverflow.com/questions/9776527/merging-without-whitespace-conflicts).

**Comment by domenkozar** [comment]
Oh that's neat. Let me test a potential merge and how well this works.

**Comment by domenkozar** [comment]
@lukego thanks for that parameter, I see no other blocks from merging this.

**Pull request merged**
